### ISSUE TITLE
Libhandy widgets look different than expected

### ISSUE THREAD

**Issue by GustavoPeredo** [Selenium-H/Personalize#1]
First I need to say: TYSM for this extension, it is awesome!!
That said... There is a problem. Applications that use libhandy widgets look different than expected. Here is an example with GNOME Clocks:
![Captura de tela de 2021-02-20 08-43-47](https://user-images.githubusercontent.com/30641461/108594325-2cbf8f80-7358-11eb-88f1-e2ab9deeed1f.png)
You can see that that the buttons on the bottom and titlebar look different than usual. Comparison with how it looks with default Adwaita.
![Captura de tela de 2021-02-20 08-47-56](https://user-images.githubusercontent.com/30641461/108594353-62fd0f00-7358-11eb-9938-ab8f34dd6acc.png)
~~If I'm not mistaken, this is caused by using Adwaita's stable version instead of the most recent one...~~
I was mistaken, compiling latest Adwaita theme and using an unmodified css or extracting directly from your system results in the same bug.

**Comment by GustavoPeredo** [comment]
Good news! Apparently there is a patch you have to add in order to have the widgets to behave correcty!
![Captura de tela de 2021-02-20 15-40-56](https://user-images.githubusercontent.com/30641461/108605307-10404900-7392-11eb-9faf-d140fe2144b1.png)

I simply added the lines from [Yaru's Adwaita upstream libhandy theme](https://github.com/ubuntu/yaru/blob/master/gtk/upstream/libhandy/themes/Adwaita.css) and bam! Now I have to say that unfortunately you would have to have different generators for light and dark variants, otherwise the app looks broken:
![Captura de tela de 2021-02-20 15-43-35](https://user-images.githubusercontent.com/30641461/108605365-71681c80-7392-11eb-9681-2e841cb2ba08.png)
Using the correct patch (Adwaita-dark.css from the same repository) fixes the issue, tho:
![Captura de tela de 2021-02-20 15-46-37](https://user-images.githubusercontent.com/30641461/108605448-dcb1ee80-7392-11eb-9524-c32c12fd8d44.png)

**Comment by GustavoPeredo** [comment]
Also, I've noticed that by default only gtk.css is generated (inside the theme's folder), are you willing to implement gtk.css and gtk-dark.css? This way dark applications, such as GNOME Boxes, behave as intended, or was intentional design to only write gtk.css?

**Comment by Selenium-H** [comment]
> are you willing to implement gtk.css and gtk-dark.css?

Yes. 



> There is a problem. Applications that use libhandy widgets look different than expected. Here is an example with GNOME Clocks

Working on it. I'll update once done.

**Comment by GustavoPeredo** [comment]
Awesome!! Thanks!

**Comment by Selenium-H** [comment]
Added support for libhandy widgets with last commit.
