### ISSUE TITLE
Not working on gnome 40

### ISSUE THREAD

**Issue by radical4ever** [Selenium-H/Personalize#4]
I tried to use this awesome extension (experimental branch) on gnome 40 but the extension doesn't work i cant active the extension, and the issue is this one:

The settings of extension personalize@Selenium-H had an error:
```
Error: No property margin on Gjs_PrefsWindowForTheme_PersonalizeExtension
```

Stack trace:
```
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
_parent@resource:///org/gnome/gjs/modules/script/_legacy.js:40:21
_init@/home/julianfaustino/.local/share/gnome-shell/extensions/personalize@Selenium-H/prefs.js:226:10
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
_parent@resource:///org/gnome/gjs/modules/script/_legacy.js:40:21
_init@/home/julianfaustino/.local/share/gnome-shell/extensions/personalize@Selenium-H/prefs.js:345:10
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
_init@/home/julianfaustino/.local/share/gnome-shell/extensions/personalize@Selenium-H/prefs.js:203:25
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
buildPrefsWidget@/home/julianfaustino/.local/share/gnome-shell/extensions/personalize@Selenium-H/prefs.js:34:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Selenium-H** [comment]
Please restart the `GNOME Shell` after updating. If you are using `wayland`, log out and log in back. For `Xorg`, Press `Alt` + `F2` ->  Type `r` -> Press `Enter`.

**Comment by radical4ever** [comment]
nope didnt work too

**Comment by radical4ever** [comment]
i leave the output of the build :
Installing Extension personalize@Selenium-H
Installation Path /home/julianfaustino/.local/share/gnome-shell/extensions

Removing any Older Version ...   Done
Copying New Version ...          cp: no se puede efectuar `stat' sobre 'locale': No existe el fichero o el directorio
Done
Compiling Schemas ...            Done
Creating Translations ...        ./INSTALL.sh: línea 67: cd: locale: No existe el fichero o el directorio
msgfmt: error al abrir el fichero "schemas//personalize.po" para lectura: No existe el fichero o el directorio

Extension Installed, Translations not done.

Restart GNOME Shell ( Alt + F2 , Press r , Press Enter ).
Enable this extension using GNOME Tweak Tool.

**Comment by radical4ever** [comment]
i remember that i forgot to put experimental while cloning the file xD i finally got it! and btw i found a new issue :b
